### ISSUE TITLE
The reply is not getting the contacting user

### ISSUE THREAD

**Issue by Abduvakilov** [ohld/telegram-support-bot#5]
The app is deployed on heroku. If a user that needs support starts the bot the bot is messaging hand emoji and I am getting the contacted user info. I am getting forwarded messages of users from the bot. But if I reply to the forwarded message my message is being forwarded to myself and the owner of the message is not gettin my message.
I have tried to restart all dynos. How can I fix the problem?

**Comment by DavianMachete** [comment]
I have the same problem...

**Comment by Hazerott** [comment]
same

**Comment by Akiyamka** [comment]
Same, Logs from heroku
```bash
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
   handler.handle_update(update, self, check, context)

   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
   return self.callback(update, context)

   File "/app/handlers.py", line 47, in forward_to_user
   user_id = update.message.reply_to_message.forward_from.id

   AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by starrabb1t** [comment]
SOLUTION:
in `handlers.py` change line with `user_id` declaration to this:
`user_id = update.message.reply_to_message.forward_from.id`

**Comment by Abduvakilov** [comment]
Do yo mean line 54?
https://github.com/ohld/telegram-support-bot/blob/93782bf01ed53548c8e2898f9867c2687e893b2d/handlers.py#L54

**Comment by starrabb1t** [comment]
oh, I see
it's seems to be okay now. i have old version

**Comment by fayzrakhmanov2000** [comment]
Can somebody help please? I changed line 54 to user_id = update.message.reply_to_message.forward_from.id but it didn't help

**Comment by fayzrakhmanov2000** [comment]
> SOLUTION: in `handlers.py` change line with `user_id` declaration to this: `user_id = update.message.reply_to_message.forward_from.id`

Can you help please? I changed line 54 to user_id = update.message.reply_to_message.forward_from.id but it didn't help
